<table class='INt ranking sortable'>
    <thead>
        <tr>
    		<th>順位<br>Rank</th>
    		<th>名前<br>Player</th>
    		<th>☆</th>
    		<th>◇</th>
    		<th>△</th>
    	</tr>
    </thead>
	<tbody class='ranking'>
    	<tr>
    		<td>1</td>
    		<td>水性すらいむ</td>
    		<td>19</td>
    		<td>12</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>2</td>
    		<td>LET</td>
    		<td>19</td>
    		<td>7</td>
    		<td>5</td>
    	</tr>
    	<tr>
    		<td>3</td>
    		<td>夏花火</td>
    		<td>9</td>
    		<td>4</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>4</td>
    		<td>Ｋ・Ｇ</td>
    		<td>8</td>
    		<td>10</td>
    		<td>5</td>
    	</tr>
    	<tr>
    		<td>5</td>
    		<td>A.War</td>
    		<td>6</td>
    		<td>2</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>6</td>
    		<td>coco</td>
    		<td>6</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>7</td>
    		<td>PALM</td>
    		<td>4</td>
    		<td>4</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>8</td>
    		<td>Eternal</td>
    		<td>3</td>
    		<td>8</td>
    		<td>6</td>
    	</tr>
    	<tr>
    		<td>9</td>
    		<td>Clio</td>
    		<td>3</td>
    		<td>0</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>10</td>
    		<td>YABU</td>
    		<td>2</td>
    		<td>3</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>11</td>
    		<td>R@P</td>
    		<td>2</td>
    		<td>1</td>
    		<td>3</td>
    	</tr>
    	<tr>
    		<td>12</td>
    		<td>ASL</td>
    		<td>2</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>13</td>
    		<td>Lain</td>
    		<td>2</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>14</td>
    		<td>绿绿可柚</td>
    		<td>2</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>14</td>
    		<td>st</td>
    		<td>2</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>14</td>
    		<td>Poitaro</td>
    		<td>2</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>17</td>
    		<td>KWS</td>
    		<td>1</td>
    		<td>4</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>18</td>
    		<td>SET</td>
    		<td>1</td>
    		<td>2</td>
    		<td>4</td>
    	</tr>
    	<tr>
    		<td>18</td>
    		<td>KLG</td>
    		<td>1</td>
    		<td>2</td>
    		<td>4</td>
    	</tr>
    	<tr>
    		<td>20</td>
    		<td>Seppo Hovi</td>
    		<td>1</td>
    		<td>2</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>20</td>
    		<td>AQUA</td>
    		<td>1</td>
    		<td>2</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>22</td>
    		<td>Atu</td>
    		<td>1</td>
    		<td>1</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>23</td>
    		<td>KENO</td>
    		<td>1</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>24</td>
    		<td>ガブリエラ</td>
    		<td>1</td>
    		<td>0</td>
    		<td>5</td>
    	</tr>
    	<tr>
    		<td>25</td>
    		<td>yeswill</td>
    		<td>1</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>25</td>
    		<td>vcz</td>
    		<td>1</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>25</td>
    		<td>asbr</td>
    		<td>1</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>25</td>
    		<td>asaburo</td>
    		<td>1</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>25</td>
    		<td>S</td>
    		<td>1</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>25</td>
    		<td>PRNO</td>
    		<td>1</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>25</td>
    		<td>Levea</td>
    		<td>1</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>25</td>
    		<td>Alan</td>
    		<td>1</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>25</td>
    		<td>AM</td>
    		<td>1</td>
    		<td>0</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>34</td>
    		<td>RDMR</td>
    		<td>0</td>
    		<td>7</td>
    		<td>4</td>
    	</tr>
    	<tr>
    		<td>35</td>
    		<td>ASAPIN</td>
    		<td>0</td>
    		<td>3</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>36</td>
    		<td>ラビ</td>
    		<td>0</td>
    		<td>2</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>36</td>
    		<td>Suika</td>
    		<td>0</td>
    		<td>2</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>38</td>
    		<td>たかぼう</td>
    		<td>0</td>
    		<td>2</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>38</td>
    		<td>Garm</td>
    		<td>0</td>
    		<td>2</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>38</td>
    		<td>Doin</td>
    		<td>0</td>
    		<td>2</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>41</td>
    		<td>elixir</td>
    		<td>0</td>
    		<td>1</td>
    		<td>4</td>
    	</tr>
    	<tr>
    		<td>41</td>
    		<td>YSJ</td>
    		<td>0</td>
    		<td>1</td>
    		<td>4</td>
    	</tr>
    	<tr>
    		<td>43</td>
    		<td>Lim</td>
    		<td>0</td>
    		<td>1</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>44</td>
    		<td>＄</td>
    		<td>0</td>
    		<td>1</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>44</td>
    		<td>dgrsBT</td>
    		<td>0</td>
    		<td>1</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>44</td>
    		<td>Mokou Sheep</td>
    		<td>0</td>
    		<td>1</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>44</td>
    		<td>HS参謀</td>
    		<td>0</td>
    		<td>1</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>44</td>
    		<td>Dual</td>
    		<td>0</td>
    		<td>1</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>専属メイド</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>ゆうてん</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>ぼん</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>ごみふね</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>からあげクン</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>wm</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>YMLO</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>Y.S</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>LSS</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>KML...</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>ICHI</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>GRP@げろっぴ</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>GEPPO</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>49</td>
    		<td>Crim.S.</td>
    		<td>0</td>
    		<td>1</td>
    		<td>0</td>
    	</tr>
    	<tr>
    		<td>63</td>
    		<td>佐天泪子</td>
    		<td>0</td>
    		<td>0</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>63</td>
    		<td>もゆみ</td>
    		<td>0</td>
    		<td>0</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>63</td>
    		<td>tomo</td>
    		<td>0</td>
    		<td>0</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>63</td>
    		<td>moby</td>
    		<td>0</td>
    		<td>0</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>63</td>
    		<td>less</td>
    		<td>0</td>
    		<td>0</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>63</td>
    		<td>WGO</td>
    		<td>0</td>
    		<td>0</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>63</td>
    		<td>TAK.</td>
    		<td>0</td>
    		<td>0</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>63</td>
    		<td>IFR</td>
    		<td>0</td>
    		<td>0</td>
    		<td>2</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>黒鍵</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>悠然</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>リデラ</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>アイスプライス</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>まいける</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>くらげ</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>t1100</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>ranranru</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>hikari</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>farewall</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>YAMA</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>Toy</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>Sakurei</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>SOC</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>R/</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>MtPK</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>MKG.</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>LAHsty</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>EITH</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>CV:○○○○</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>BPIG</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    	<tr>
    		<td>71</td>
    		<td>1</td>
    		<td>0</td>
    		<td>0</td>
    		<td>1</td>
    	</tr>
    </tbody>
</table>
