<div id='wrap' class='wrap'>
    <?php echo wrap_top() ?>
    <p class='wide'><strong>Effective date:</strong> 16 December 2019</p>
    <p>Maribel Hearn's Touhou Portal ("us", "we", or "our") operates the maribelhearn.com
    website (hereinafter referred to as the "Service").</p>
    <p>This page informs you of our policies regarding the collection, use,
    and disclosure of personal data when you use our Service and the choices you have associated with that data.
    The Privacy Policy  for Maribel Hearn's Touhou Portal has been created with the help of
    <a href='https://www.termsfeed.com/privacy-policy-generator/'>Privacy Policy Generator</a>.</p>
    <p>We use your data to provide and improve the Service. By using the Service,
    you agree to the collection and use of information in accordance with this policy.</p>

    <h2>Definitions</h2>

    <h4>Service</h4>
    <p>Service is the maribelhearn.com website operated by Maribel Hearn's Touhou Portal</p>

    <h4>Personal Data</h4>
    <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>

    <h4>Usage Data</h4>
    <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>

    <h4>Cookies</h4>
    <p>Cookies are small files stored on your device (computer or mobile device).</p>

    <h2>Information Collection and Use</h2>
    <p>We do <strong>not</strong> collect any type of information on users.</p>

    <h3>Types of Data Collected</h3>

    <h4>Personal Data</h4>
    <p>While using our Service, we will <strong>not</strong> ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data").</p>

    <h4>Tracking & Cookies Data</h4>
    <p>We do <strong>not</strong> use cookies or similar tracking technologies to track the activity on our Service.</p>

    <h2>Security of Data</h2>
    <p>The security of your data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

    <h2>Links to Other Sites</h2>
    <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
    <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

    <h2>Children's Privacy</h2>
    <p>Our Service does <strong>not</strong> address anyone under the age of 18 ("Children").</p>
    <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our server.</p>

    <h2>Changes to This Privacy Policy</h2>
    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
    <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

    <h2>Contact Us</h2>
    <p>If you have any questions about this Privacy Policy, please contact us:</p>
    <ul>
        <li>By email: maribelhearn@disroot.org</li>
    </ul>

    <footer><strong><a href='#top'>Back to Top</a></strong></footer>
</div>
